# ----- Replace disk_types and vm_types -----
- type: replace
  path: /instance_groups/name=consul/persistent_disk_type
  value: default
- type: replace
  path: /instance_groups/name=consul/vm_type
  value: default
- type: replace
  path: /instance_groups/name=etcd/persistent_disk_type
  value: default
- type: replace
  path: /instance_groups/name=etcd/vm_type
  value: default
- type: replace
  path: /instance_groups/name=mysql/persistent_disk_type
  value: default
- type: replace
  path: /instance_groups/name=mysql/vm_type
  value: default
- type: replace
  path: /instance_groups/name=blobstore/persistent_disk_type
  value: default
- type: replace
  path: /instance_groups/name=blobstore/vm_type
  value: default
- type: replace
  path: /instance_groups/name=uaa/vm_type
  value: default
- type: replace
  path: /instance_groups/name=diego-bbs/vm_type
  value: default
- type: replace
  path: /instance_groups/name=diego-brain/vm_type
  value: default
- type: replace
  path: /instance_groups/name=diego-cell/vm_type
  value: large
- type: replace
  path: /instance_groups/name=router/vm_type
  value: default
- type: replace
  path: /instance_groups/name=route-emitter/vm_type
  value: default
- type: replace
  path: /instance_groups/name=cc_clock/vm_type
  value: default
- type: replace
  path: /instance_groups/name=cc_bridge/vm_type
  value: default
- type: replace
  path: /instance_groups/name=doppler/vm_type
  value: default
- type: replace
  path: /instance_groups/name=log_controller/vm_type
  value: default
- type: replace
  path: /instance_groups/name=api/vm_type
  value: large
