---
resources:
- name: cf-deployment-master
  type: git
  icon: github-box
  source:
    branch: master
    uri: git@github.com:cloudfoundry/cf-deployment.git
    private_key: ((cf_deployment_readwrite_deploy_key.private_key))

- name: runtime-ci
  type: git
  icon: github-box
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git

- name: stemcell
  type: bosh-io-stemcell
  icon: dna
  source:
    name: bosh-google-kvm-ubuntu-xenial-go_agent

jobs:
- name: update-stemcell-minor
  public: true
  plan:
  - in_parallel:
    - get: cf-deployment-master
    - get: runtime-ci
    - get: stemcell
      params:
        tarball: false
  - task: update-stemcell-minor
    file: runtime-ci/tasks/update-base-manifest-stemcell/task.yml
    input_mapping:
      cf-deployment: cf-deployment-master
