#@ load("@ytt:data", "data")

#@ load("bbl-down.lib.yml", "bbl_down")
#@ load("bbl-up.lib.yml", "bbl_up")
#@ load("delete-deployment.lib.yml", "delete_deployment")
#@ load("manage-gcp-dns.lib.yml", "manage_gcp_dns")

---
resource_types:
- name: stemcell-version-bump
  type: docker-image
  source:
    repository: relintdockerhubpushbot/stemcell-version-bump-resource

resources:
- name: cf-deployment-concourse-tasks
  type: git
  icon: github-box
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: cf-deployment-master
  type: git
  icon: github-box
  source:
    branch: master
    uri: git@github.com:weymanf/cf-deployment.git
    private_key: ((weyman-cfd-deploy-key.private_key))

- name: cf-deployment-develop
  type: git
  icon: github-box
  source:
    branch: develop
    uri: git@github.com:weymanf/cf-deployment.git
    private_key: ((weyman-cfd-deploy-key.private_key))

- name: cf-deployment-version
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/cf-relint-ci-semver.git
    branch: minor-stemcell-test
    private_key: ((cf_relint_ci_semver_readwrite_deploy_key.private_key))
    git_user: "CF MEGA BOT <cf-mega@pivotal.io>"
    file: cf-deployment-version

- name: cf-deployment-release
  type: github-release
  source:
    owner: weymanf
    repository: cf-deployment
    access_token: ((weymanf_repo_access_token))

- name: pre-dev-pool
  type: pool
  icon: pool
  source:
    uri: git@github.com:cloudfoundry/relint-ci-pools
    branch: master
    pool: update-release-pool
    private_key: ((relint_ci_pools_readwrite_deploy_key.private_key))

- name: relint-envs
  type: git
  icon: github-box
  source:
    branch: master
    uri: git@github.com:cloudfoundry/relint-envs.git
    private_key: ((hagrid_env_readwrite_deploy_key.private_key))

- name: runtime-ci
  type: git
  icon: github-box
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git

- name: stemcell
  type: bosh-io-stemcell
  icon: dna
  source:
    name: bosh-google-kvm-ubuntu-xenial-go_agent
    version_family: "456.latest"

- name: stemcell-version-bump-detect
  type: stemcell-version-bump
  icon: dna
  source:
    json_key: ((concourse_gcp_service_account_json))
    bucket_name: cf-deployment-stemcell-bump-test
    file_name: stemcell-version

- name: stemcell-version-bump-minor
  type: stemcell-version-bump
  icon: dna
  source:
    json_key: ((concourse_gcp_service_account_json))
    bucket_name: cf-deployment-stemcell-bump-test
    file_name: stemcell-version
    type_filter: minor

- name: stemcell-version-bump-major
  type: stemcell-version-bump
  icon: dna
  source:
    json_key: ((concourse_gcp_service_account_json))
    bucket_name: cf-deployment-stemcell-bump-test
    file_name: stemcell-version
    type_filter: major

jobs:
#@ env = "pre-dev"
- name: update-stemcell-minor
  public: true
  plan:
  - put: pre-dev-pool
    params: {acquire: true}
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: cf-deployment-master
    - get: relint-envs
    - get: runtime-ci
    - get: stemcell
      params:
        tarball: false
    - get: cf-deployment-version
      params: {bump: minor}
  - task: update-stemcell-minor
    file: runtime-ci/tasks/update-base-manifest-stemcell/task.yml
    input_mapping:
      cf-deployment: cf-deployment-master
    output_mapping:
      updated-cf-deployment: updated-cf-deployment-master
  - do:
    - #@ bbl_up(env)
    - #@ manage_gcp_dns("add", env)
    - do:
      - task: combine-vars-files
        file: runtime-ci/tasks/combine-inputs/task.yml
        input_mapping:
          first-input: cf-deployment-master
          second-input: relint-envs
        output_mapping:
          combined-inputs: combined-vars-files
      - task: deploy-cf
        file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
        input_mapping:
          bbl-state: relint-envs
          cf-deployment: updated-cf-deployment-master
          ops-files: updated-cf-deployment-master
          vars-files: combined-vars-files
          pool-lock: pre-dev-pool
        params:
          BBL_JSON_CONFIG: pool-lock/metadata
          OPS_FILES: |
            operations/use-compiled-releases.yml
            operations/experimental/fast-deploy-with-downtime-and-danger.yml
          REGENERATE_CREDENTIALS: false
          BOSH_DEPLOY_ARGS: "--parallel 50"
      - task: ensure-api-healthy
        file: runtime-ci/tasks/ensure-api-healthy/task.yml
        input_mapping:
          pool-lock: pre-dev-pool
          cats-integration-config: relint-envs
        params:
          BBL_JSON_CONFIG: pool-lock/metadata
      - task: run-errand-smoke-tests
        file: cf-deployment-concourse-tasks/run-errand/task.yml
        input_mapping:
          bbl-state: relint-envs
          pool-lock: pre-dev-pool
        params:
          BBL_JSON_CONFIG: pool-lock/metadata
          ERRAND_NAME: smoke-tests
      - task: generate-cf-deployment-release-notes-template
        file: runtime-ci/tasks/cf-deployment-minor-stemcell-bump-release-notes/task.yml
        input_mapping:
          release-version: cf-deployment-version
      - task: update-cf-deployment-manifest-version
        file: runtime-ci/tasks/record-cfd-version-in-manifest/task.yml
        input_mapping:
          cf-deployment-release-candidate: updated-cf-deployment-master
        output_mapping:
          cf-deployment-rc-with-updated-version: cf-deployment-master-with-updated-manifest-version
      - put: cf-deployment-master
        params:
          repository: cf-deployment-master-with-updated-manifest-version
          tag: cf-deployment-version/version
          tag_prefix: v
      - put: cf-deployment-release
        params:
          name: cf-deployment-minor-stemcell-bump-release-notes/name.txt
          tag: cf-deployment-version/version
          tag_prefix: v
          body: cf-deployment-minor-stemcell-bump-release-notes/body.txt
      - put: cf-deployment-version
        params: {bump: minor}
      - put: cf-deployment-develop
        params:
          repository: cf-deployment-master-with-updated-manifest-version
          merge: true
      ensure:
        do:
        - #@ delete_deployment(env)
        - #@ manage_gcp_dns("remove", env)
        - #@ bbl_down(env)
    ensure:
      do:
      - put: pre-dev-pool
        params: {release: pre-dev-pool}

- name: detect-stemcell-bump
  plan:
  - get: stemcell
    trigger: true
  - get: cf-deployment-master
  - get: runtime-ci
  - task: detect-stemcell-bump
    file: runtime-ci/tasks/detect-stemcell-bump/task.yml
  - put: stemcell-version-bump-detect
    params:
      stemcell-bump-type-file: stemcell-bump-type
      stemcell-bump-version-file: stemcell/version

- name: test-minor-stemcell-version-bump
  plan:
  - get: stemcell-version-bump-minor
    trigger: true
  - get: stemcell
    passed:
    - detect-stemcell-bump

- name: test-major-stemcell-version-bump
  plan:
  - get: stemcell-version-bump-major
    trigger: true
  - get: stemcell
    passed:
    - detect-stemcell-bump
